sudo: false
language: ruby
rvm:
- 2.1
- 2.2
- 2.3
- 2.4
env:
  global:
  - TZ=Europe/London
  - DB_PASSWORD=""
before_install:
- export TZ=Europe/London
script:
- bundle exec rspec -fd -b -P ./spec/**/*_spec.rb
- ./quality.sh
services:
- postgresql
addons:
  # This is the lowest version que supports
  postgresql: "9.5"
cache: bundler
notifications:
  email: false
